#[cfg(feature = "matchmaking")]
pub mod game_server;
#[cfg(feature = "matchmaking")]
pub mod matchmaking_command;
#[cfg(feature = "matchmaking")]
pub mod matchmaking_command_dal;
#[cfg(feature = "matchmaking")]
pub mod matchmaking_completed_notification;
#[cfg(feature = "matchmaking")]
pub mod matchmaking_failed_notification;
#[cfg(feature = "matchmaking")]
pub mod matchmaking_servers_full_notification;
#[cfg(feature = "matchmaking")]
pub mod matchmaking_session;
#[cfg(feature = "matchmaking")]
pub mod matchmaking_ticket;
#[cfg(feature = "matchmaking")]
pub mod redis_key_names;
#[cfg(feature = "matchmaking")]
pub mod matchmaking_activate_session_notification;
