#[cfg(feature = "dal")]
pub mod game_server_dal;
#[cfg(feature = "dal")]
pub mod generic_dal;
#[cfg(feature = "dal")]
pub mod id_generator_dal;
#[cfg(feature = "dal")]
pub mod master_entity;
#[cfg(feature = "dal")]
pub mod matchmaking_average_waiting_time_dal;
#[cfg(feature = "dal")]
pub mod matchmaking_session_dal;
#[cfg(feature = "dal")]
pub mod matchmaking_settings_dal;
#[cfg(feature = "dal")]
pub mod matchmaking_ticket_dal;
#[cfg(feature = "dal")]
pub mod mongo_db_collection;
